[package]
name = "quinn-ffi"
version = "0.1.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

# generates the cbinding, i.e. the headerfile
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
quinn = "0.1"

[build-dependencies]
cbindgen = "0.6"